// Copies the org system's generated token CSS into creator/tokens/org/ (the org repo is not modified) and mirrors its
// .dark/.light class blocks as [data-theme] scopes, so Creator aliases resolve under the same theme switch.
// The copy is verbatim; org-theme.css is derived from it.  Drift: build-org-layer.mjs compares the recorded sha with the repo file.
import fs from "node:fs"; import crypto from "node:crypto"; import path from "node:path";
const ORG = path.resolve(new URL("../..", import.meta.url).pathname);
const src = fs.readFileSync(path.join(ORG, "generated/tokens.css"), "utf8");
const dir = new URL("../tokens/org/", import.meta.url); fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(new URL("tokens.css", dir), src);
const block = (cls) => (src.match(new RegExp(`\\n\\.${cls}\\s*\\{([^}]*)\\}`)) ?? [])[1] ?? "";
const theme = `/* org-theme.css - GENERATED by tools/sync-org.mjs: the org system's .dark/.light blocks re-scoped to [data-theme] so one theme switch drives both token layers. */\n:root,\n[data-theme="light"] {${block("light")}}\n[data-theme="dark"] {${block("dark")}}\n`;
fs.writeFileSync(new URL("org-theme.css", dir), theme);
const sha = crypto.createHash("sha256").update(src).digest("hex").slice(0, 16);
fs.writeFileSync(new URL("SOURCE.json", dir), JSON.stringify({ source: "airtime-design-system/generated/tokens.css", sha256_16: sha, note: "verbatim copy; never edit" }, null, 1));
console.log("org tokens synced", sha);
