// Hand-curated metadata for the extraction: (1) DERIVED tokens (literals in the recipes/primitives that the app does
// not name), (2) how Creator roles map to the org system (airtime-design-system) for the "same / differs / creator-only"
// pass, (3) text-style role mapping.  Every entry names its source; values were checked against data/ledger.json.
const R = "apps/airtime-creator/src/ui/recipes/", P = "apps/airtime-creator/src/creator/sidebar/primitives/", S = "apps/airtime-creator/src/creator/sidebar/";
const d = (id, category, type, value, desc, file, find, extra = {}) => ({ id, css: "--cr-" + id.replace(/\./g, "-"), category, type, value, desc, source: { file, find }, ...extra });
const both = (light, dark) => ({ light, dark });
const one = (v) => ({ value: v });
export const DERIVED = [
  // opacity
  d("opacity.disabled", "opacity", "number", one("0.4"), "Disabled control and unwired placeholder: the whole control dims once.", R + "sidebarRowRecipe.ts", "_disabled: { opacity: 0.4"),
  d("opacity.dimmed", "opacity", "number", one("0.45"), "A hidden layer's thumbnail fades.", P + "ThumbRow.tsx", "opacity={dimmed ? 0.45 : 1}"),
  d("opacity.locked-grip", "opacity", "number", one("0.3"), "A locked layer's grip glyph.", P + "ThumbRow.tsx", "opacity={locked ? 0.3 : 1}"),
  // sidebar type
  d("font-size.sidebar", "font-sizes", "dimension", one("12px"), "Sidebar root type size, inherited by every descendant.", S + "Sidebar.tsx", 'fontSize="12px"'),
  d("line-height.sidebar", "line-heights", "dimension", one("15px"), "Sidebar root line height: every 30px row is two of these.", S + "Sidebar.tsx", 'lineHeight="15px"'),
  d("letter-spacing.sidebar", "letter-spacings", "dimension", one("-0.036px"), "Sidebar root tracking (prototype computed -0.04px at 12px).", S + "Sidebar.tsx", 'letterSpacing="-0.036px"'),
  // colours (literals)
  d("color.pill-fill", "colors", "color", one("rgba(255, 255, 255, 0.12)"), "Dropdown value pill: the same translucent lift in both themes.", R + "sidebarFieldRecipe.ts", 'bg: "rgba(255, 255, 255, 0.12)"'),
  d("color.swatch-ring-dot", "colors", "color", one("rgba(255, 255, 255, 0.24)"), "1px inset ring on tint dots and the color-well dot (white in both themes).", P + "Swatches.tsx", '"inset 0 0 0 1px rgba(255, 255, 255, 0.24)"'),
  d("color.swatch-ring-tile", "colors", "color", one("rgba(255, 255, 255, 0.16)"), "1px ring around background tiles.", P + "Swatches.tsx", '"0 0 0 1px rgba(255, 255, 255, 0.16)"'),
  d("color.swatch-none-slash", "colors", "color", one("rgb(255, 69, 58)"), "The red diagonal of the empty (None) dot.", P + "Swatches.tsx", "rgb(255, 69, 58)"),
  d("color.swatch-none-fill", "colors", "color", one("rgba(255, 255, 255, 0.08)"), "Fill behind the None dot's slash.", P + "Swatches.tsx", 'bgColor: "rgba(255, 255, 255, 0.08)"'),
  d("color.chip-ground", "colors", "color", one("#E6E6EC"), "Drop-shadow preset chip: the miniature slide's ground (content, same in both themes).", P + "Dropdown.tsx", 'bg="#E6E6EC"'),
  d("color.checker-a", "colors", "color", one("#FFFFFF"), "Transparency checker, light square.", P + "TransparencyChecker.tsx", "#FFFFFF 0% 25%"),
  d("color.checker-b", "colors", "color", one("#D4D4DA"), "Transparency checker, dark square.", P + "TransparencyChecker.tsx", "#D4D4DA 0% 50%"),
  d("color.thumb-selected-fill", "colors", "color", one("rgba(255, 255, 255, 0.18)"), "Thumb slot inside a selected (accent) list row.", P + "ThumbRow.tsx", 'rgba(255, 255, 255, 0.18)'),
  d("color.thumb-selected-ring", "colors", "color", one("rgba(255, 255, 255, 0.3)"), "Thumb hairline inside a selected list row.", P + "ThumbRow.tsx", "rgba(255, 255, 255, 0.3)"),
  d("color.knob", "colors", "color", one("#FFFFFF"), "Slider and switch knobs are white in both themes.", P + "SliderRow.tsx", "bg: \"white\""),
  // shadows (literals)
  d("shadow.sidebar-card", "shadows", "shadow", one("0 0 0 1px rgba(255, 255, 255, 0.08), 0 20px 40px 0 rgba(0, 0, 0, 0.35)"), "The sidebar card itself: a 1px white hairline and a 20/40 drop. (The declared token shadow.sidebar is not what renders.)", S + "Sidebar.tsx", "0 0 0 1px rgba(255, 255, 255, 0.08), 0 20px 40px"),
  d("shadow.action-button", "shadows", "shadow", one("inset 0 0.5px 0 0 var(--cr-color-edge-in), 0 1px 2px rgba(0, 0, 0, 0.2)"), "Action button raised edge: top highlight plus 1px drop.", R + "sidebarRowRecipe.ts", 'boxShadow: "inset 0 0.5px 0 0 {colors.edge.in}, 0 1px 2px rgba(0, 0, 0, 0.2)"'),
  d("shadow.pill", "shadows", "shadow", one("inset 0 0.5px 0 0 rgba(255, 255, 255, 0.16), 0 1px 2px rgba(0, 0, 0, 0.2)"), "Dropdown value pill.", R + "sidebarFieldRecipe.ts", 'boxShadow: "inset 0 0.5px 0 0 rgba(255, 255, 255, 0.16), 0 1px 2px'),
  d("shadow.field-well", "shadows", "shadow", one("inset 0 0 0 0.5px var(--cr-color-line)"), "Value field well: hairline ring.", R + "sidebarFieldRecipe.ts", 'boxShadow: "inset 0 0 0 0.5px {colors.line}"'),
  d("shadow.field-well-hover", "shadows", "shadow", one("inset 0 0 0 0.5px var(--cr-color-line-strong)"), "Value field well on hover.", R + "sidebarFieldRecipe.ts", '_hover: { boxShadow: "inset 0 0 0 0.5px {colors.line.strong}"'),
  d("shadow.field-focus", "shadows", "shadow", one("inset 0 0 0 0.5px var(--cr-color-accent-solid), 0 0 0 3px color-mix(in srgb, var(--cr-color-accent-solid) 22%, transparent)"), "Value field focus: 0.5px accent line inside a 3px 22% halo (softer than shadow.focus).", R + "sidebarFieldRecipe.ts", "const focusRing ="),
  d("shadow.segment-track-sidebar", "shadows", "shadow", one("inset 0 0 0 0.5px var(--cr-color-line), inset 0 1px 2px 0 rgba(0, 0, 0, 0.06)"), "Segmented and shape tracks: hairline ring and 1px inner drop.", R + "sidebarSegmentSlotRecipe.ts", "const track ="),
  d("shadow.popover", "shadows", "shadow", one("0 0 0 0.5px var(--cr-color-edge-out), 0 8px 24px rgba(0, 0, 0, 0.45)"), "Dropdown panel and color-well popover.", P + "Dropdown.tsx", 'boxShadow="0 0 0 0.5px {colors.edge.out}, 0 8px 24px rgba(0, 0, 0, 0.45)"'),
  d("shadow.popover-range", "shadows", "shadow", one("0 0 0 0.5px var(--cr-color-edge-out), 0 8px 20px rgba(0, 0, 0, 0.45)"), "Range popup under a value field.", P + "SliderRow.tsx", '0 8px 20px rgba(0, 0, 0, 0.45)'),
  d("shadow.swatch-selected-tile", "shadows", "shadow", one("0 0 0 2px var(--cr-color-accent-solid)"), "Selected background tile: 2px accent ring.", P + "Swatches.tsx", 'boxShadow: circle'),
  d("shadow.swatch-selected-dot", "shadows", "shadow", one("inset 0 0 0 1px rgba(255, 255, 255, 0.3), 0 0 0 2.5px var(--cr-color-accent-solid)"), "Selected tint dot: 2.5px accent ring outside a white inner hairline.", P + "Swatches.tsx", "0 0 0 2.5px {colors.accent.solid}"),
  d("shadow.range-track", "shadows", "shadow", one("inset 0 1px 1.5px rgba(0, 0, 0, 0.3)"), "Range slider track (4px, state.active fill).", P + "SliderRow.tsx", "inset 0 1px 1.5px rgba(0, 0, 0, 0.3)"),
  d("shadow.range-thumb", "shadows", "shadow", one("0 0 0 0.5px rgba(0, 0, 0, 0.18), 0 1px 3px rgba(0, 0, 0, 0.38)"), "Range slider thumb (15px white).", P + "SliderRow.tsx", "0 0 0 0.5px rgba(0, 0, 0, 0.18), 0 1px 3px rgba(0, 0, 0, 0.38)"),
  d("shadow.switch-track", "shadows", "shadow", one("inset 0 1px 2px rgba(0, 0, 0, 0.1)"), "Switch track (30x18).", P + "ThumbRow.tsx", "inset 0 1px 2px rgba(0, 0, 0, 0.1)"),
  d("shadow.switch-knob", "shadows", "shadow", one("0 0 0 0.5px rgba(0, 0, 0, 0.14), 0 1px 2px rgba(0, 0, 0, 0.28)"), "Switch knob (14px white).", P + "ThumbRow.tsx", "0 0 0 0.5px rgba(0, 0, 0, 0.14), 0 1px 2px rgba(0, 0, 0, 0.28)"),
  d("shadow.thumb-ring", "shadows", "shadow", one("inset 0 0 0 0.5px var(--cr-color-line-strong)"), "Thumbnail frame hairline (layer, layout, logo).", P + "ThumbFrame.tsx", "inset 0 0 0 0.5px {colors.line.strong}"),
  d("shadow.drop-before", "shadows", "shadow", one("inset 0 2px 0 var(--cr-color-state-drop-indicator)"), "Layer drag: insertion line on a row's top edge (bottom: inset 0 -2px).", P + "ThumbRow.tsx", 'inset 0 2px 0 {colors.state.dropIndicator}'),
  // sizes (anatomy aliases of the Chakra numeric ladder)
  d("size.row", "sizes", "dimension", one("var(--cr-size-creator-sidebar-row)"), "Row height, 30px (min-height).", R + "sidebarRowRecipe.ts", 'minH: "creator.sidebarRow"', { orgNote: "Org rows are 32px/40px (rows.css)." }),
  d("size.control", "sizes", "dimension", one("var(--cr-size-creator-sidebar-control)"), "Segment, value field, pill and tool height, 24px.", R + "sidebarSegmentSlotRecipe.ts", 'h: "creator.sidebarControl"'),
  d("size.icon-row", "sizes", "dimension", one("var(--cr-size-5)"), "Row glyph box: 20px. Glyph painted with fill: currentColor.", P + "Row.tsx", 'boxSize="5"'),
  d("size.icon-action", "sizes", "dimension", one("var(--cr-size-4-5)"), "Action button glyph: 18px.", P + "Actions.tsx", 'boxSize="4.5"'),
  d("size.icon-header", "sizes", "dimension", one("var(--cr-size-4)"), "Header toggle glyph: 16px.", P + "IconToggle.tsx", 'size === "back" ? "5" : "4"'),
  d("size.icon-inline", "sizes", "dimension", one("var(--cr-size-3-5)"), "Layer-row eye/lock glyph: 14px.", P + "IconToggle.tsx", 'inline ? "3.5"'),
  d("size.icon-shape", "sizes", "dimension", one("22px"), "Shape segment glyph.", R + "sidebarSegmentSlotRecipe.ts", '"& svg": { boxSize: "22px" }'),
  d("size.icon-chevron", "sizes", "dimension", one("var(--cr-size-creator-device-chevron)"), "Pill chevron: 9px.", R + "sidebarFieldRecipe.ts", '"& svg": { boxSize: "9px"'),
  d("size.hit-header", "sizes", "dimension", one("26px"), "Header IconToggle box (back, hide, lock); 22px inline.", P + "IconToggle.tsx", 'boxSize={inline ? "22px" : "26px"}'),
  d("size.hit-inline", "sizes", "dimension", one("22px"), "Layer-row eye/lock box.", P + "IconToggle.tsx", 'boxSize={inline ? "22px" : "26px"}'),
  d("size.pane-header", "sizes", "dimension", one("var(--cr-size-11)"), "Pane header band: 44px.", R + "sidebarSectionSlotRecipe.ts", 'h: "11"'),
  d("size.thumb-row", "sizes", "dimension", one("var(--cr-size-9)"), "List row min height: 36px.", P + "ThumbRow.tsx", 'minH="9"'),
  d("size.thumb-w", "sizes", "dimension", one("var(--cr-size-12)"), "Row thumbnail slot: 48px wide.", P + "ThumbRow.tsx", 'w="12"'),
  d("size.thumb-h", "sizes", "dimension", one("var(--cr-size-7)"), "Row thumbnail slot: 28px tall.", P + "ThumbRow.tsx", 'h="7"'),
  d("size.color-dot", "sizes", "dimension", one("var(--cr-size-5)"), "Color-well dot: 20px.", P + "ColorWellRow.tsx", 'boxSize="5"'),
  d("size.tint-dot", "sizes", "dimension", one("var(--cr-size-6)"), "Tint dot in a swatch grid: 24px.", P + "Swatches.tsx", 'w={circle ? "6"'),
  d("size.switch-w", "sizes", "dimension", one("30px"), "Switch track width (hit box 34x26).", P + "ThumbRow.tsx", 'w="30px"'),
  d("size.switch-h", "sizes", "dimension", one("18px"), "Switch track height.", P + "ThumbRow.tsx", 'h="18px"'),
  d("size.switch-knob", "sizes", "dimension", one("14px"), "Switch knob.", P + "ThumbRow.tsx", 'boxSize="14px"'),
  d("size.range-thumb", "sizes", "dimension", one("15px"), "Range thumb.", P + "SliderRow.tsx", "boxSize: \"15px\""),
  d("size.range-track", "sizes", "dimension", one("4px"), "Range track height.", P + "SliderRow.tsx", 'height: "4px"'),
  d("size.popup-range-w", "sizes", "dimension", one("250px"), "Range popup width.", P + "SliderRow.tsx", 'w="250px"'),
  d("size.popup-color-w", "sizes", "dimension", one("var(--cr-size-60)"), "Color-well popover width: 240px.", P + "ColorWellRow.tsx", 'w="60"'),
  d("size.popup-grid-col", "sizes", "dimension", one("56px"), "Dropdown grid panel: three 56px columns.", P + "Dropdown.tsx", "repeat(3, 56px)"),
  d("size.popup-gutter", "sizes", "dimension", one("4px"), "Gap between the row's edge and its popup.", P + "popupPlacement.ts", "gutter: 4"),
  d("size.popup-edge", "sizes", "dimension", one("16px"), "Popup keeps this far inside the sidebar card (flip/slide boundary).", P + "popupPlacement.ts", "overflowPadding: 16"),
  d("size.field-value-w", "sizes", "dimension", one("54px"), "Value field width; the wide (hex) field is 112px.", R + "sidebarFieldRecipe.ts", 'w: "54px"'),
  d("size.field-wide-w", "sizes", "dimension", one("112px"), "Wide value field (hex).", R + "sidebarFieldRecipe.ts", 'w: "112px"'),
  // motion
  d("transition.control", "transitions", "transition", one("background var(--cr-duration-fast) var(--cr-easing-settle), color var(--cr-duration-fast) var(--cr-easing-settle)"), "Segments, rows, fields: colour changes on 160ms settle.", R + "sidebarSegmentSlotRecipe.ts", 'transitionProperty: "background, color"'),
  d("transition.swatch", "transitions", "transition", one("box-shadow var(--cr-duration-fast) var(--cr-easing-spring), transform var(--cr-duration-fast) var(--cr-easing-spring)"), "Swatch hover scale and ring: 160ms spring.", P + "Swatches.tsx", 'transitionTimingFunction="spring"'),
];

// ---- org relationship: creator role -> org token, with the reason. creatorOnly:true means the org has no such role.
export const ORG_ROLE = {
  "--cr-color-bg": { org: "--color-background-primary", why: "window ground; org is a teal-tinted near-black/#F5F5F5, creator is neutral macOS grey" },
  "--cr-color-bg-panel": { org: "--color-background-secondary", why: "content surface" },
  "--cr-color-bg-subtle": { org: "--color-background-tertiary", why: "recessed well" },
  "--cr-color-background-primary": { org: "--color-background-primary", why: "legacy chrome ground (header, stage) still on the org-era values" },
  "--cr-color-background-tertiary": { org: "--color-background-tertiary", why: "legacy chrome tertiary" },
  "--cr-color-content-primary": { org: "--color-content-primary", why: "primary ink; creator is pure black/white, org is #000E14 / white" },
  "--cr-color-content-secondary": { org: "--color-content-secondary", why: "secondary ink" },
  "--cr-color-content-tertiary": { org: "--color-content-tertiary", why: "tertiary ink" },
  "--cr-color-action-primary": { org: "--color-accent-teal", orgLight: "--color-accent-teal", why: "legacy Airtime teal action (light org value is the darker #1A7580, which creator keeps as action.secondary)" },
  "--cr-color-action-secondary": { org: "--color-accent-teal", orgLight: "--color-accent-teal", orgDark: "--color-accent-teal", why: "teal, light-theme variant of the org accent" },
  "--cr-color-action-destructive": { org: "--color-accent-destructive", why: "destructive red; creator uses #ff715c/#ff7661, org #D6402F/#FF6D4C" },
  "--cr-color-danger-solid": { org: "--color-accent-destructive", why: "system red for recording/destruction; org destructive is warmer" },
  "--cr-color-state-hover": { org: "--color-highlight-secondary", why: "hover wash; creator 5.5%/8%, org 4%/16%" },
  "--cr-color-state-active": { org: "--color-highlight-primary", why: "active wash; creator 10%/13%, org 8%/8%" },
  "--cr-color-highlight-primary": { org: "--color-highlight-primary", why: "legacy highlight token" },
  "--cr-color-highlight-secondary": { org: "--color-highlight-secondary", why: "legacy highlight token" },
  "--cr-color-accent-solid": { creatorOnly: true, why: "org accent is teal (#79DDE8 / #1A7580); creator's selection accent is macOS system blue, spent only on selection, focus and on" },
  "--cr-color-focus-ring": { creatorOnly: true, why: "org has no focus-ring colour token" },
  "--cr-shadow-sm": { org: "--shadow-small", why: "small elevation; creator adds a 0.5px edge hairline" },
  "--cr-shadow-md": { org: "--shadow-medium", why: "medium elevation" },
  "--cr-shadow-lg": { org: "--shadow-large", why: "large elevation" },
  "--cr-font-family-body": { org: "--font-family-primary", why: "system stack; creator puts SF Pro Text/Display before Helvetica, org starts with -apple-system, 'SF Pro', 'Segoe UI', Roboto" },
  "--cr-font-family-heading": { org: "--font-family-primary", why: "same stack as body" },
};
export const TEXT_ROLE = { "heading.large": "heading-large", "heading.medium": "heading-medium", "heading.small": "heading-small", "body.large": "body-large", "body.medium": "body-medium", "body.small": "body-small", button: "button-default" };
