import { S, esc, provBadge } from "./lib.js";
export function audit(root) {
  const A = S.audit; if (!A) { root.innerHTML = '<section id="audit"><h2>Audit</h2><p class="callout">data/audit.json missing: run tools/audit-join.mjs.</p></section>'; return; }
  const h = A.headline, d = A.docs, B = h.declsByBucket, R = h.rulesByBucket;
  const pct = (s) => parseFloat(s.split("=")[1]);
  const bar = (o) => `<div class="bar" title="ds / redesign / legacy / unmatched (of attributable)"><i class="b-ds" style="width:${pct(o.ds)}%"></i><i class="b-rd" style="width:${pct(o.redesign)}%"></i><i class="b-lg" style="width:${pct(o.legacy)}%"></i><i class="b-un" style="width:${pct(o.unmatched)}%"></i></div>`;
  // per-pattern table
  const pats = Object.entries(A.patterns).filter(([, v]) => v.attributable).sort((a, b) => b[1].unmatched + b[1].dead - (a[1].unmatched + a[1].dead));
  const files = h.fileRows.filter((f) => f.unused).slice(0, 9);
  root.innerHTML = `<section id="audit"><h2>Audit: where the Creator's CSS comes from, and what is unused</h2>
  <p class="lede">The CSS audit (code <code>${h.code}</code>, generated ${h.generated}, ${h.states} states) crawled the live app in light and dark, matched every rule against the DOM and forced pseudo states, and value-matched every declaration against the org design system, the creator-v2 redesign explorations, legacy stylesheets and Chakra's defaults. This page joins that evidence to every token and pattern.</p>
  <div class="callout" style="background:color-mix(in srgb, var(--cr-color-accent-solid) 12%, transparent)"><b>The org system is not a clean parent of the Creator's values.</b> Only <b>${h.dsExclusive[0]} declarations (${h.dsExclusive[1]}% of attributable)</b> match the DS <em>exclusively</em>; another ${h.dsPlusExplorations[0]} (${h.dsPlusExplorations[1]}%) match only the DS plus generic exploration files. ${h.dsExclusive[2]} (${h.dsExclusive[3]}%) match the DS at all, but almost all of those values are also in a redesign source (round numbers such as 6px, 8px, 500). ${h.dsExclusive[4]} (${h.dsExclusive[5]}%) match a redesign source and not the DS; in the sidebar ${h.sidebarAnyMatch}% of declarations match some redesign source. "DS" in the tables below is where the DS wins the tie, so it is an upper bound on derivation.</div>
  <h3>Headline numbers</h3>
  <table class="spec" style="max-width:1000px"><tr><th>Measure</th><th>Value</th></tr>
  <tr><td>CSS rules / style rules</td><td>${h.rules.total} / ${h.rules.style}</td></tr>
  <tr><td>Unused rules (never matched in any crawled state or forced pseudo state)</td><td><b>${h.rules.unusedPct}</b>; style rules ${h.rules.unusedStyle} of ${h.rules.style}; confidence HIGH ${h.byConf.HIGH} / MEDIUM ${h.byConf.MEDIUM} / LOW ${h.byConf.LOW}</td></tr>
  <tr><td>Legacy teleport stylesheets</td><td><b>${h.legacyUnused[0]}% unused</b> (${h.legacyUnused[1]}/${h.legacyUnused[2]} rules); whole files at zero: atomic.css (136), pickr theme (59), format_bar.css (17), popover.css (2)</td></tr>
  <tr><td>Dead declarations (in used rules, lose the cascade everywhere sampled)</td><td><b>${h.neverEffective.decls}</b> of ${h.neverEffective.of} (${(100 * h.neverEffective.decls / h.neverEffective.of).toFixed(1)}%); ${h.neverEffective.fullyOverriddenRules} used rules have no effective declaration at all</td></tr>
  <tr><td>Unreferenced custom properties</td><td><b>${h.customProps.unreferenced}</b> of ${h.customProps.defined} (${(100 * h.customProps.unreferenced / h.customProps.defined).toFixed(1)}%), mostly Chakra's emitted colour/spacing/size ladder</td></tr>
  <tr><td>Duplicated declaration blocks</td><td>${h.dupGroups} groups of rules with identical declarations under different selectors</td></tr>
  <tr><td>One-off literals (bucket 4, unmatched)</td><td>${h.oneOffs[0]} declarations (${h.oneOffs[1]}%); top properties: ${esc(h.oneOffs[2])}</td></tr></table>
  <h3>Rules and declarations by provenance bucket</h3>
  <p class="lede">Percentages are of <em>attributable</em> items (structural declarations such as <code>display:flex</code> have no value provenance and are excluded). Rulings applied: every redesign exploration folder counts as the creator-v2 lineage; named legacy and third-party stylesheets always land in the legacy bucket even when their values equal DS tokens.</p>
  <table class="spec" style="max-width:1100px"><tr><th></th><th>${provBadge("airtime-design-system")}</th><th>${provBadge("creator-v2 redesign")}</th><th>creator-v2: r3 only</th><th>${provBadge("legacy/other")}</th><th>${provBadge("unmatched")}</th><th>notes</th></tr>
  <tr><td>Rules (dominant bucket)</td><td>${R.ds}</td><td>${R.redesign}</td><td>${R.r3only}</td><td>${R.legacy}</td><td>${R.unmatched}</td><td class="muted">${R.notes}</td></tr>
  <tr><td>Declarations</td><td>${B.ds}</td><td>${B.redesign}</td><td>${B.r3only}</td><td>${B.legacy}</td><td>${B.unmatched}</td><td class="muted">${B.notes}</td></tr></table>
  <div style="margin:8px 0">${bar(B)}<div class="muted" style="font-size:10px">declarations: <span class="org prov-ds">DS</span> <span class="org prov-rd">redesign</span> <span class="org prov-lg">legacy</span> <span class="org prov-un">unmatched</span>. Redesign sub-buckets: r2-a-dock/r2-shell 30.0%, r2-b-select 0.5%, other explorations 0.4% of attributable (r3-unified has 0.0% exclusive matches because its values are shared with r2-a).</div></div>
  <h3>Unused CSS by file</h3>
  <table class="spec" style="max-width:800px"><tr><th>File</th><th>Rules</th><th>Unused</th></tr>${files.map((f) => `<tr><td class="src">${esc(f.file)}</td><td>${f.total}</td><td>${f.unused} (${Math.round((100 * f.unused) / f.total)}%)</td></tr>`).join("")}</table>
  <h3>Patterns ranked by what to clean</h3>
  <p class="lede">Distinct declarations attributed to each pattern's component files (the rendering component owns recipe output). Details, with the offending declarations, are in each pattern card's "Audit" block.</p>
  <table class="spec"><tr><th>Pattern</th><th>Declarations</th><th>DS-match</th><th>Redesign</th><th>Legacy</th><th>One-off literals</th><th>Dead</th></tr>${pats.map(([id, v]) => `<tr><td><a href="#${id}">${id}</a></td><td>${v.total}</td><td>${v.ds} (${v.dsExclusive} excl.)</td><td>${v.redesign}</td><td>${v.legacyN}</td><td>${v.unmatched}</td><td>${v.dead}</td></tr>`).join("")}</table>
  <h3>Method</h3>
  <p class="lede">Headless Chromium and CDP, signed out, fake camera; fixtures for Presenter, Text, Image, GIF, Video, Screenshare and Name tag selected by real stage clicks; every clickable in the sidebar, TopBar, band, tray and stage clicked, hovered, typed into, right-clicked and Tab-walked; one nested popup level; six viewport sizes; light and dark (and OS-mismatched and reduced-motion runs). Rules are matched with <code>querySelectorAll</code> at every snapshot; hover/active/focus rules are matched under <code>CSS.forcePseudoState</code>; the cascade per element signature comes from <code>CSS.getMatchedStylesForNode</code>. Declarations are value-matched (colours normalised across formats, lengths to px, shadows per layer) with <code>var()</code> resolved per theme.</p>
  <h3>Limits</h3>
  <ul class="lede"><li>"Unused" means matched by no element in any snapshot; sub-second transient states, drag ghosts and real <code>:disabled/:invalid/:checked</code> states that never appeared can be false positives (MEDIUM and LOW confidence).</li><li><b>Unreachable states:</b> signed-in states (real account menu, saved-presentation library, session-expired and migration banners), OS file choosers (Upload, Import, Replace), real recordings and the Video Editor with data, mic-denied and device-disconnect variants, GIPHY/Media Library remote content, print, forced-colors, RTL, touch-only.</li><li>Provenance is value matching, not proof of derivation; round numbers exist in every source. Legacy-wins is a rule about the stylesheet, not the value.</li><li>Dev-server build only (emotion inserts one style per rule); production CSS may be structured differently.</li><li>Pattern attribution here is by rendering component file (recipe output is attributed to the component that mounted it), so a pattern that shares a component with others shares its numbers; <code>ax-button</code>, <code>ax-tooltip</code> and <code>sb-states</code> have no attributable file (the tooltip wrapper file hosts every wrapped control, so its numbers would not describe the tooltip).</li><li>Token provenance uses the audit row for the token's custom-property declaration (both themes); derived (literal) tokens are joined by file and value and may be missing when the literal is part of a longer declaration.</li></ul>
  <h3>Reports</h3>
  <ul class="lede"><li><code>${d.report}</code>: executive summary, top findings, method, coverage, limits</li><li><code>${d.provenance}</code>: buckets, per-area and per-file tables, section 9 per-declaration matching table, section 10 comparison with the earlier value-wins figures</li><li><code>${d.fileByFile}</code>: every stylesheet and file, duplicated blocks, never-effective declarations</li><li><code>${d.unused}</code>: every unused rule with reason and confidence</li><li><code>${d.data}</code>: <code>provenance-declarations.tsv.gz</code> (21,950 rows, the source of this page's joins), rules.jsonl, declarations.jsonl.gz, sources.json</li></ul></section>`;
}
