import { pattern, icon, mm, si } from "./lib.js";
const G = (cap, html) => ({ cap, html });
const gb = (inner, label, cls = "", attrs = "") => `<button type="button" class="cr-btn0 cr-gbtn ${cls}" aria-label="${label}" ${attrs}>${inner}</button>`;
const pill = () => `<div class="cr-glass" role="toolbar" aria-label="Presenter controls">${gb(mm("MaskSquare"), "Shape")}${gb(icon("Border"), "Background")}${gb(icon("Border"), "Border")}<span class="cr-glass-sep"></span>${gb(mm("AlignLeft"), "Alignment")}${gb(mm("LayersRaise"), "Arrange")}${gb(mm("DropShadow"), "Drop shadow")}${gb(mm("Ellipsis"), "More")}${gb(mm("ExpandDiagonal"), "Fullscreen")}</div>`;
const gitem = (ic, text, cls = "", attrs = "") => `<button type="button" class="cr-btn0 cr-gitem ${cls}" ${attrs}>${ic}<span style="flex:1">${text}</span></button>`;
const ST = [["default", ""], ["hover", "is-hover"], ["pressed", "is-pressed"], ["focus-visible", "is-focus"], ["open", "is-open"], ["disabled", "is-disabled"]];
const onGlass = (inner) => `<div style="padding:20px;border-radius:8px;background:linear-gradient(135deg,#1d3b5c,#5a2d59 60%,#2f6b5e)">${inner}</div>`;
export function stage(root) {
  const P = [];
  P.push(pattern({
    id: "st-pill", title: "Selection pill and its buttons", org: ["creator-only", "The org system has no floating stage toolbar."], raw: true,
    note: "A glass toolbar under the selected object: <b>always dark</b> (selection.material, blur 28 saturate 200%) regardless of the shell theme, radius xl, padding 3, gap 2, with the selection-bar shadow (edge highlight, hairline, two drops). Buttons are the `stage` variant: 28px, radius lg, white at .96; hover selection.hover, open/pressed selection.active, press scales .92, disabled selection.disabled. Rendered button type is 16px/500 (the recipe intends 13px). The light and dark stages below are identical on purpose.",
    css: ["cr-glass", "cr-gbtn", "cr-glass-sep"], src: ["st.pill"],
    anatomy: [["Pill", "radius xl, padding 3, gap 2, bg selection.material", "color.selection-material, shadow.selection-bar, blur.selection-bar"], ["Button", "h28, min-w 28, padding 0 9, radius lg, glyph 15px", "size.7, radius.lg"], ["Hover / open", "selection.hover (.11) / selection.active (.20)", "color.selection-hover, color.selection-active"], ["Separator", "1x16, selection.line", "color.selection-line"], ["Disabled", "text selection.disabled (no opacity)", "color.selection-disabled"]],
    groups: [G("assembled (over a stage)", onGlass(pill())), G("button states", onGlass(`<div style="display:flex;gap:14px;align-items:center;flex-wrap:wrap">${ST.map(([n, c]) => `<div style="display:flex;flex-direction:column;align-items:center;gap:6px"><div class="cr-glass">${gb(mm("MaskSquare"), n, c, n === "disabled" ? "disabled" : "")}</div><span style="font-size:10px;color:var(--cr-color-selection-muted)">${n}</span></div>`).join("")}</div>`))],
  }));
  P.push(pattern({
    id: "st-popover", title: "Stage popover: menu rows, options, swatches, slider", org: ["creator-only", "-"], raw: true,
    note: "A pill button opens a glass popover (menu variant `stage`: radius 4xl (22), padding 8, 220-328px wide, selection-menu shadow, blur 34). Contents: a muted 11px uppercase title, rows (`stageRow`: 32px, 13/500, hover selection.hover, destructive red rgb(255,92,92)), option tiles (`stageOption`: column, muted, pressed selection.active), 24px color swatches (selected: 2.5px teal ring), and slider fields (52px value well on selection.track). Placement: below the pill, flipped above near the stage bottom (stageControlPositioning).",
    css: ["cr-gmenu", "cr-gitem", "cr-gopt", "cr-gswatch", "cr-gslider", "cr-gsep"], src: ["st.popover"],
    anatomy: [["Popover", "radius 4xl, padding 8, glass, min 220 / max 328", "radius.4xl, size.creator.selection-menu-min, size.creator.selection-menu-max, shadow.selection-menu, blur.selection-menu"], ["Row", "h32, padding 0 7, 13/500, radius md", "size.8"], ["Destructive", "rgb(255,92,92); hover .14, press .24 wash", "color.selection-destructive, color.selection-destructive-hover"], ["Option", "column, padding 10 6, 11px, radius lg", ""], ["Swatch", "24px; selected 2.5px teal ring", ""], ["Value well", "52x24, radius 6, selection.track, inset ring .13", "radius.room-tile, color.selection-track"], ["Separator", "1px selection.line, margin 8 3", ""]],
    groups: [G("popover", onGlass(`<div class="cr-gmenu" style="width:300px"><div class="title">Border</div>${gitem("", "Width")}<div class="cr-gslider"><div class="top"><span>Width</span><span class="val">4</span></div><div class="track"><i style="width:40%"></i><b style="left:40%"></b></div></div><div class="cr-gsep"></div><div class="cr-gopts"><button class="cr-btn0 cr-gopt is-selected">${mm("MaskSquare")}Square</button><button class="cr-btn0 cr-gopt">${mm("MaskCircle")}Circle</button><button class="cr-btn0 cr-gopt is-hover">${mm("MaskHexagon")}Hex</button><button class="cr-btn0 cr-gopt is-disabled" disabled>${mm("MaskRectangle")}Rect</button></div><div class="cr-gsep"></div><div style="display:flex;gap:8px;padding:4px 7px">${["#FFFFFF", "#3D7BFF", "#FF4B3E", "#3FCF6A"].map((c, i) => `<button class="cr-btn0 cr-gswatch ${i === 1 ? "is-selected" : ""}" style="background:${c}" aria-label="${c}"></button>`).join("")}</div><div class="cr-gsep"></div>${gitem(icon("Copy"), "Copy settings", "is-hover")}${gitem(icon("TrashStroke"), "Delete", "", "data-destructive")}${gitem(icon("Paste"), "Paste settings", "is-disabled", "disabled")}</div>`)), G("row states", onGlass(`<div class="cr-gmenu" style="width:240px">${["default", "hover", "pressed", "focus-visible", "disabled"].map((n) => gitem(icon("Copy"), n, { hover: "is-hover", pressed: "is-pressed", "focus-visible": "is-focus", disabled: "is-disabled" }[n] ?? "", n === "disabled" ? "disabled" : "")).join("")}${gitem(icon("TrashStroke"), "destructive hover", "is-hover", "data-destructive")}</div>`))],
  }));
  const hnd = (cls, x, y, extra = "") => `<i class="cr-handle ${cls} ${extra}" style="left:${x};top:${y}"></i>`;
  const frame = (dims, inner = "") => `<div class="cr-stage-mock"><div class="obj" style="${dims}"></div><div class="cr-frame" style="${dims}"></div>${inner}</div>`;
  const D = "left:22%;top:20%;width:40%;height:44%;";
  const corners = (l, t, w, h) => hnd("is-nw", l, t) + hnd("is-ne", `calc(${l} + ${w})`, t) + hnd("is-ne", l, `calc(${t} + ${h})`) + hnd("is-nw", `calc(${l} + ${w})`, `calc(${t} + ${h})`);
  const edges = (l, t, w, h) => hnd("is-ns", `calc(${l} + ${w} / 2)`, t) + hnd("is-ns", `calc(${l} + ${w} / 2)`, `calc(${t} + ${h})`) + hnd("is-ew", l, `calc(${t} + ${h} / 2)`) + hnd("is-ew", `calc(${l} + ${w})`, `calc(${t} + ${h} / 2)`);
  P.push(pattern({
    id: "st-overlay", title: "Selection frame and resize handles", org: ["creator-only", "Legacy teleport overlay CSS, not part of any org token set."], raw: true,
    note: "The selected object gets a 2px frame in <b>legacy Airtime teal #99E5EE</b> (--frame-color: var(--action-hover)) with a black 6px glow and 1px contact shadow, and ten-pixel white square handles (2px teal border, radius 2, 0 1px 4px .18 shadow): four corners (diagonal resize cursors) and four edges. The overlay is drawn by teleport/stage/objects/overlay.css, outside Chakra, so the teal does not follow the Creator accent.",
    css: ["cr-frame", "cr-handle", "cr-stage-mock"], src: ["st.overlay"],
    anatomy: [["Frame", "2px solid stage-frame; drop-shadow(0 0 6px #000) drop-shadow(0 1px 2px .18)", "color.stage-frame, size.frame-width"], ["Handle", "10px, white, 2px stage-frame border, radius 2, shadow", "size.handle, radius.handle, shadow.handle, color.handle-fill"], ["Cursors", "nwse / nesw / ns / ew-resize", ""]],
    groups: [G("selected object with handles", `<div style="max-width:420px">${frame(D, corners("22%", "20%", "40%", "44%") + edges("22%", "20%", "40%", "44%"))}</div>`), G("selected object with the selection pill", `<div style="max-width:420px">${frame(D, corners("22%", "20%", "40%", "44%") + `<div style="position:absolute;left:50%;top:72%;transform:translateX(-50%)">${pill()}</div>`)}</div>`)],
  }));
  P.push(pattern({
    id: "st-crop", title: "Crop UI (edge handles and option bar)", org: ["creator-only", "-"], raw: true,
    note: "Crop mode keeps the frame and swaps edge handles for elongated knobs (10x20 on horizontal edges, 20x10 on vertical ones) and dims the cropped-away area. Its option bar is legacy teleport UI: pill-shaped (radius 20), buttons 32px on rgba(0,0,0,.6), 14px/590 white, 1px rgba(255,255,255,.15) dividers, pressed rgba(0,0,0,.4) with 200-grey text, disabled 128-grey.",
    css: ["cr-cropbar", "cr-handle", "cr-dim"], src: ["st.overlay"],
    anatomy: [["Crop handle", "edge knob 10x20 / 20x10 (--knob-diameter x2)", "size.handle"], ["Dim", "rgba(0,0,0,.5) outside the crop box (mock)", ""], ["Bar", "radius 20, 1px rgba(255,255,255,.1) border, blur 5", ""], ["Button", "h32, padding 4 16, 14px/590, white on rgba(0,0,0,.6)", ""]],
    groups: [G("crop mode", `<div style="max-width:420px">${frame(D, `<div class="cr-dim" style="left:0;top:0;right:0;height:20%"></div><div class="cr-dim" style="left:0;bottom:0;right:0;height:36%"></div><div class="cr-dim" style="left:0;top:20%;width:22%;height:44%"></div><div class="cr-dim" style="right:0;top:20%;width:38%;height:44%"></div>` + hnd("is-ns crop-h", "42%", "20%") + hnd("is-ns crop-h", "42%", "64%") + hnd("is-ew crop-v", "22%", "42%") + hnd("is-ew crop-v", "62%", "42%"))}</div>`), G("option bar states", `<div style="display:flex;gap:14px;flex-wrap:wrap"><div class="cr-cropbar"><button class="cr-btn0">Cancel</button><button class="cr-btn0 is-pressed">Reset</button><button class="cr-btn0">Done</button></div><div class="cr-cropbar"><button class="cr-btn0 is-disabled" disabled>Reset</button><button class="cr-btn0">Done</button></div></div>`)],
  }));
  const line = (cls, pos) => `<i class="cr-guide ${cls}" style="${pos}"></i>`;
  P.push(pattern({
    id: "st-guides", title: "Alignment guides and grid", org: ["creator-only", "-"], raw: true,
    note: "While dragging, the stage shows anchor snap lines (thirds and centre) in white, a red #E55242 line for the guide the object is currently snapping to, and layer snap lines only while snapping. The grid canvas fills rgba(127,127,127,.65). Drawn as SVG by teleport/stage/objects/alignment_grid.js.",
    css: ["cr-guide", "cr-gridfill"], src: ["st.overlay"],
    anatomy: [["Anchor line", "white", "color.stage-guide"], ["Hit line", "#E55242", "color.stage-guide-hit"], ["Grid fill", "rgba(127,127,127,.65)", "color.stage-grid-fill"]],
    groups: [G("dragging near centre", `<div style="max-width:420px">${frame("left:30%;top:24%;width:40%;height:40%;", line("is-v", "left:33.33%") + line("is-v", "left:66.66%") + line("is-h", "top:33.33%") + line("is-h", "top:66.66%") + line("is-v is-hit", "left:50%") + line("is-h is-hit", "top:44%"))}</div>`)],
  }));
  root.innerHTML = `<section id="stage"><h2>Stage</h2><p class="lede">Everything drawn over the stage: the selection pill and its popovers (Chakra recipes on always-dark glass), and the resize handles, crop UI and guides (legacy teleport CSS). The stage itself is a 16:9 well with an 8px radius.</p>${P.join("")}</section>`;
}
